name: Generate ASCII Artwork

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List Repo Files
              run: ls -ltra

            - name: Executin Shell Script
              run: |
                  chmod +x ascii-script.sh
                  ./ascii-script.sh
    test_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List Repo Files
              run: ls -ltra

            - name: Executin Shell Script
              run: |
                  chmod +x ascii-script.sh
                  ./ascii-script.sh
    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: List Repo Files
              run: ls -ltra
            
            - name: Executin Shell Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh              
